version: "3.9"

services:

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: shopapi
      POSTGRES_PASSWORD: shopapi123
      POSTGRES_DB: shopapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shopapi"]
      interval: 5s
      timeout: 5s
      retries: 5

  product-service:
    build:
      context: ./services/product-service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://shopapi:shopapi123@postgres:5432/shopapi
      AWS_ENDPOINT_URL: http://host.docker.internal:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      S3_BUCKET: shopapi-product-images
    depends_on:
      postgres:
        condition: service_healthy

  order-service:
    build:
      context: ./services/order-service
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://shopapi:shopapi123@postgres:5432/shopapi
      PRODUCT_SERVICE_URL: http://product-service:8000
    depends_on:
      postgres:
        condition: service_healthy
      product-service:
        condition: service_started

volumes:
  postgres_data:
