apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: prod

patches:
  - path: replicas-patch.yaml
  - path: resources-patch.yaml

# Prod: ALWAYS use a pinned version tag — NEVER use "latest"
# The CD promotion workflow updates these on every git tag push
images:
  - name: product-service
    newTag: "0.1.1"
    newName: ghcr.io/sirbank/shopapi/product-service
  - name: order-service
    newTag: "v0.1.1"
    newName: ghcr.io/sirbank/shopapi/order-service

labels:
  - pairs:
      environment: prod
      managed-by: argocd
    includeSelectors: false
