apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: shopapi
  POSTGRES_PASSWORD: shopapi123
  POSTGRES_DB: shopapi
  DATABASE_URL: postgresql://shopapi:shopapi123@postgres:5432/shopapi